name: Fetch manifests
description: Downloads and unzips all build manifest artifacts for the current workflow run.
author: Snapcrafters
branding:
  icon: code
  color: orange

inputs:
  token:
    description: "A token with permissions to get artifacts from this repository"
    required: true

runs:
  using: composite
  steps:
    - name: Setup Node 24
      uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6
      with:
        node-version: "24.20.0"
    - name: Run fetch-manifests
      shell: bash
      env:
        INPUT_TOKEN: ${{ inputs.token }}
      run: node "${{ github.action_path }}/dist/index.cjs"
