name: Promote snap
description: Promotes a given set of revisions to a specified channel
author: Snapcrafters
branding:
  icon: trending-up
  color: orange

inputs:
  channel:
    description: "The channel to promote the snap to"
    default: "latest/stable"
    required: false
  github-token:
    description: "A token with permissions to write issues on the repository"
    required: true
  snapcraft-project-root:
    description: "The root of the snapcraft project, where the `snapcraft` command would usually be executed from."
    required: false
  snapcraft-channel:
    description: "The channel to install snapcraft from"
    default: latest/stable
    required: false
  store-token:
    description: "A token with permissions to upload to the specified channel"
    required: true

runs:
  using: composite
  steps:
    - name: Setup Node 24
      uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6
      with:
        node-version: "24.20.0"
    - name: Run promote-to-stable
      shell: bash
      env:
        INPUT_CHANNEL: ${{ inputs.channel }}
        INPUT_GITHUB_TOKEN: ${{ inputs.github-token }}
        INPUT_SNAPCRAFT_PROJECT_ROOT: ${{ inputs.snapcraft-project-root }}
        INPUT_SNAPCRAFT_CHANNEL: ${{ inputs.snapcraft-channel }}
        INPUT_STORE_TOKEN: ${{ inputs.store-token }}
      run: node "${{ github.action_path }}/dist/index.cjs"
