name: Promote snap
description: Promotes a given set of revisions to a specified channel
author: Snapcrafters
branding:
  icon: trending-up
  color: orange

inputs:
  channel:
    description: "The channel to promote the snap to"
    default: "latest/stable"
    required: false
  github-token:
    description: "A token with permissions to write issues on the repository"
    required: true
  snapcraft-project-root:
    description: "The root of the snapcraft project, where the `snapcraft` command would usually be executed from."
    required: false
  snapcraft-channel:
    description: "The channel to install snapcraft from"
    default: latest/stable
    required: false
  store-token:
    description: "A token with permissions to upload to the specified channel"
    required: true

runs:
  using: composite
  steps:
    - uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38
      with:
        node-version: "24"
    - shell: bash
      env:
        CI_PHASE: validate
      run: node "$GITHUB_ACTION_PATH/dist/index.cjs"
    - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803
    - shell: bash
      env:
        SNAPCRAFT_CHANNEL: ${{ inputs.snapcraft-channel }}
      run: sudo snap install snapcraft --channel "$SNAPCRAFT_CHANNEL" --classic
    - shell: bash
      env:
        CI_PHASE: run
        INPUT_CHANNEL: ${{ inputs.channel }}
        INPUT_GITHUB_TOKEN: ${{ inputs.github-token }}
        INPUT_SNAPCRAFT_PROJECT_ROOT: ${{ inputs.snapcraft-project-root }}
        INPUT_SNAPCRAFT_CHANNEL: ${{ inputs.snapcraft-channel }}
        INPUT_STORE_TOKEN: ${{ inputs.store-token }}
      run: node "$GITHUB_ACTION_PATH/dist/index.cjs"
      id: promote
