name: Review Snap
description: Review a built Snap package using the same tools as the Snap Store
author: Snapcrafters
branding:
  icon: check-circle
  color: orange

inputs:
  is-classic:
    description: "Set this to 'true' if you are reviewing a classic snap"
    required: false
  plugs:
    description: "The file holding plugs declarations as json to override default snap permissions"
    required: false
  slots:
    description: "The file holding slots declarations as json to override default snap permissions"
    required: false
  snap:
    description: "The snap file to review"
    required: true

runs:
  using: composite
  steps:
    - uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38
      with:
        node-version: "24"
    - shell: bash
      env:
        CI_PHASE: validate
      run: node "$GITHUB_ACTION_PATH/dist/index.cjs"
    - name: Install review-tools
      shell: bash
      run: "if ! snap list review-tools &>/dev/null; then\n  sudo snap install review-tools\nfi\n"
    - name: Review the snap
      shell: bash
      env:
        snap_file: ${{ inputs.snap }}
        plugs_file: ${{ inputs.plugs }}
        slots_file: ${{ inputs.slots }}
        is_classic: ${{ inputs.is-classic }}
      run:
        "args=()\nif [[ -n \"${plugs_file}\" ]]; then\n  args+=(\"--plugs\" \"${plugs_file}\")\nfi\nif [[ -n \"\
        ${slots_file}\" ]]; then\n  args+=(\"--slots\" \"${slots_file}\")\nfi\nif [[ \"${is_classic}\" == \"true\"\
        \ ]]; then\n  args+=(\"--allow-classic\")\nfi\nargs+=(\"${snap_file}\")\nreview-tools.snap-review \"${args[@]}\"\
        \n"
