name: Sync Version
description: Sync versions of a snap's applications and parts with the latest upstream versions.
author: Snapcrafters
branding:
  icon: refresh-cw
  color: orange

inputs:
  bot-email:
    description: "The email address of the bot account used to commit screenshots."
    required: false
    default: "snapforge.team@gmail.com"
  bot-name:
    description: "The name of the bot account used to commit screenshots."
    required: false
    default: "Snapcrafters Bot"
  branch:
    description: "The branch on which modifications to snapcraft.yaml should be made."
    default: "candidate"
    required: false
  snapcraft-project-root:
    description: "The root of the snapcraft project, where the `snapcraft` command would usually be executed from."
    required: false
  token:
    required: true
    description: A token with write privileges to the repository.
  update-script:
    description: "Bash script that fetches the latest version and updates the source tree as required."
    required: true

runs:
  using: composite
  steps:
    - name: Checkout the source
      uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
      with:
        token: ${{ inputs.token }}
        ref: ${{ inputs.branch }}
    - name: Setup Node 24
      uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6
      with:
        node-version: "24.20.0"
    - name: Run sync-version
      shell: bash
      env:
        INPUT_BOT_EMAIL: ${{ inputs.bot-email }}
        INPUT_BOT_NAME: ${{ inputs.bot-name }}
        INPUT_BRANCH: ${{ inputs.branch }}
        INPUT_SNAPCRAFT_PROJECT_ROOT: ${{ inputs.snapcraft-project-root }}
        INPUT_TOKEN: ${{ inputs.token }}
        INPUT_UPDATE_SCRIPT: ${{ inputs.update-script }}
      run: node "${{ github.action_path }}/dist/index.cjs"
