import { build } from "esbuild";
import { readdirSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { builtinModules } from "node:module";
const actions = readdirSync(".").filter((p) => {
  try {
    return readFileSync(`${p}/main.ts`).length > 0;
  } catch {
    return false;
  }
});
for (const action of actions) {
  const result = await build({
    entryPoints: [`${action}/main.ts`],
    bundle: true,
    platform: "node",
    target: "node24",
    format: "cjs",
    outfile: `${action}/dist/index.cjs`,
    metafile: true,
    legalComments: "inline",
    banner: { js: "// GENERATED by mise run build; do not edit." },
  });
  for (const output of Object.values(result.metafile!.outputs))
    for (const item of output.imports)
      if (item.external && !builtinModules.includes(item.path.replace(/^node:/, "")))
        throw Error(`Non-builtin external: ${item.path}`);
  const packages = [
    ...new Set(
      Object.keys(result.metafile!.inputs)
        .filter((p) => p.startsWith("node_modules/"))
        .map((p) => p.split("/")[1]),
    ),
  ].sort();
  mkdirSync(`${action}/dist`, { recursive: true });
  writeFileSync(
    `${action}/dist/licenses.txt`,
    "GENERATED dependency notices\n" +
      packages
        .map((p) => {
          const dir = `node_modules/${p}`;
          const file = readdirSync(dir).find((f) => /^licen[cs]e(\.|$)/i.test(f));
          if (!file) throw Error(`Missing license: ${p}`);
          return `\n${p}\n${readFileSync(`${dir}/${file}`, "utf8")}`;
        })
        .join("\n"),
  );
}
