name: Run tests
description: Install a snap and run specified tests for it.
author: Snapcrafters
branding:
  icon: check
  color: orange

inputs:
  channel:
    description: "The channel to install the snap from"
    default: "latest/candidate"
    required: false
  github-token:
    description: "A token with permissions to comment on issues"
    required: true
  snapcraft-project-root:
    description: "The root of the snapcraft project, where the `snapcraft` command would usually be executed from."
    required: false
  issue-number:
    description: "Number of the issue comment on."
    required: true
  test-script:
    description: "A bash script to run the tests (or simply a command)."
    required: true

runs:
  using: composite
  steps:
    - uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38
      with:
        node-version: "24"
    - shell: bash
      env:
        CI_PHASE: validate
      run: node "$GITHUB_ACTION_PATH/dist/index.cjs"
    - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803
    - shell: bash
      env:
        CI_PHASE: run
        INPUT_CHANNEL: ${{ inputs.channel }}
        INPUT_GITHUB_TOKEN: ${{ inputs.github-token }}
        INPUT_SNAPCRAFT_PROJECT_ROOT: ${{ inputs.snapcraft-project-root }}
        INPUT_ISSUE_NUMBER: ${{ inputs.issue-number }}
        INPUT_TEST_SCRIPT: ${{ inputs.test-script }}
      run: node "$GITHUB_ACTION_PATH/dist/index.cjs"
      id: tests
